# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isZero <- function(x) {
    .Call(`_Dlm_isZero`, x)
}

isWhole <- function(x) {
    .Call(`_Dlm_isWhole`, x)
}

sayHi <- function() {
    invisible(.Call(`_Dlm_sayHi`))
}

time_dlm <- function(data) {
    .Call(`_Dlm_time_dlm`, data)
}

scores <- function(stat_name, data, thresh) {
    .Call(`_Dlm_scores`, stat_name, data, thresh)
}

runtime <- function(stat_name, data, thresh) {
    .Call(`_Dlm_runtime`, stat_name, data, thresh)
}

get_sHalf <- function(stat_name, thresh) {
    .Call(`_Dlm_get_sHalf`, stat_name, thresh)
}

test_update <- function(stat_name, thresh, data) {
    invisible(.Call(`_Dlm_test_update`, stat_name, thresh, data))
}

