# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isZero <- function(x) {
    .Call(`_Dlm_isZero`, x)
}

isWhole <- function(x) {
    .Call(`_Dlm_isWhole`, x)
}

time_dlm <- function(data) {
    .Call(`_Dlm_time_dlm`, data)
}

scores <- function(stat_name, data, thresh) {
    .Call(`_Dlm_scores`, stat_name, data, thresh)
}

runtime <- function(stat_name, data, thresh) {
    .Call(`_Dlm_runtime`, stat_name, data, thresh)
}

runtimeOHA <- function(data, alpha, nu) {
    .Call(`_Dlm_runtimeOHA`, data, alpha, nu)
}

test_OHA_constr2 <- function(v, alpha, nu) {
    invisible(.Call(`_Dlm_test_OHA_constr2`, v, alpha, nu))
}

test_MHA_constr2 <- function(v, alpha, nu, i) {
    invisible(.Call(`_Dlm_test_MHA_constr2`, v, alpha, nu, i))
}

