# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isZero <- function(x) {
    .Call(`_Dlm_isZero`, x)
}

isWhole <- function(x) {
    .Call(`_Dlm_isWhole`, x)
}

time_dlm <- function(data) {
    .Call(`_Dlm_time_dlm`, data)
}

scores <- function(stat_name, data, thresh) {
    .Call(`_Dlm_scores`, stat_name, data, thresh)
}

runtime <- function(stat_name, data, thresh) {
    .Call(`_Dlm_runtime`, stat_name, data, thresh)
}

runtimeOHA <- function(data, alpha, nu) {
    .Call(`_Dlm_runtimeOHA`, data, alpha, nu)
}

test_OHA_constr2 <- function(v, alpha, nu) {
    invisible(.Call(`_Dlm_test_OHA_constr2`, v, alpha, nu))
}

test_MHA_constr2 <- function(v, alpha, nu, i) {
    invisible(.Call(`_Dlm_test_MHA_constr2`, v, alpha, nu, i))
}

test_MHA_fpr <- function(v, alpha, nu, i) {
    .Call(`_Dlm_test_MHA_fpr`, v, alpha, nu, i)
}

test_GHA_constr2 <- function(v, thresh) {
    invisible(.Call(`_Dlm_test_GHA_constr2`, v, thresh))
}

EvalStatL2 <- function(S, s, t) {
    .Call(`_Dlm_EvalStatL2`, S, s, t)
}

OneStepSearch <- function(S, shift = 0L, method = "advanced") {
    .Call(`_Dlm_OneStepSearch`, S, shift, method)
}

NaiveOS <- function(S, shift = 0L, l = -1L, s = -1L, r = -1L, stat_s = -1) {
    .Call(`_Dlm_NaiveOS`, S, shift, l, s, r, stat_s)
}

AdvancedOS <- function(S, shift) {
    .Call(`_Dlm_AdvancedOS`, S, shift)
}

